const CreateServiceTypes = {
  CREATE_SERVICE_START: 'CREATE_SERVICE_START',
  CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
  CREATE_SERVICE_ERROR: 'CREATE_SERVICE_ERROR',

  SET_LOCATION_ID: 'SET_LOCATION_ID',
};

export default CreateServiceTypes;
