const CreateServiceTypes = {
  CREATE_SERVICE_START: 'CREATE_SERVICE_START',
  CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
  CREATE_SERVICE_ERROR: 'CREATE_SERVICE_ERROR',
};

export default CreateServiceTypes;
