const DeleteServiceTypes = {
  DELETE_SERVICE_START: 'DELETE_SERVICE_START',
  DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
  DELETE_SERVICE_ERROR: 'DELETE_SERVICE_ERROR',
};

export default DeleteServiceTypes;
