const GetServiceTypes = {
  GET_SERVICE_START: 'GET_SERVICE_START',
  GET_SERVICE_SUCCESS: 'GET_SERVICE_SUCCESS',
  GET_SERVICE_ERROR: 'GET_SERVICE_ERROR',

  SET_LOADING: 'SET_LOADING',
};

export default GetServiceTypes;
