const ServiceTaxonomyTypes = {
  GET_SERVICE_TAXONOMY_START: 'GET_SERVICE_TAXONOMY_START',
  GET_SERVICE_TAXONOMY_SUCCESS: 'GET_SERVICE_TAXONOMY_SUCCESS',
  GET_SERVICE_TAXONOMY_ERROR: 'GET_SERVICE_TAXONOMY_ERROR',
};

export default ServiceTaxonomyTypes;
