const AdminBlogsTypes = {
  GET_ADMIN_POSTS_START: 'GET_ADMIN_POSTS_START',
  GET_ADMIN_DRAFTS_POSTS_SUCCESS: 'GET_ADMIN_DRAFTS_POSTS_SUCCESS',
  GET_ADMIN_POSTED_POSTS_SUCCESS: 'GET_ADMIN_POSTED_POSTS_SUCCESS',
  GET_ADMIN_POSTS_FAIL: 'GET_ADMIN_POSTS_FAIL',

  NO_RESULTS: 'NO_RESULTS',
};

export default AdminBlogsTypes;
