const AdminBlogsTypes = {
  GET_ADMIN_POSTS_START: 'GET_ADMIN_POSTS_START',
  GET_ADMIN_DRAFTS_POSTS_SUCCESS: 'GET_ADMIN_DRAFTS_POSTS_SUCCESS',
  GET_ADMIN_POSTED_POSTS_SUCCESS: 'GET_ADMIN_POSTED_POSTS_SUCCESS',
  GET_ADMIN_POSTS_FAIL: 'GET_ADMIN_POSTS_FAIL',

  SAVE_POSTS_START: 'SAVE_POSTS_START',
  SAVE_POSTS_SUCCESS: 'SAVE_POSTS_SUCCESS',
  SAVE_POSTS_FAIL: 'SAVE_POSTS_FAIL',

  DELETE_POST_START: 'DELETE_POST_START',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_FAIL: 'DELETE_POST_FAIL',

  NO_RESULTS: 'NO_RESULTS',

  HIDE_FOOTER: 'HIDE_FOOTER',
};

export default AdminBlogsTypes;
