const AdminProfileTypes = {
  UPDATE_COMPANY_START: 'UPDATE_COMPANY_START',
  UPDATE_COMPANY_SUCCESS: 'UPDATE_COMPANY_SUCCESS',
  UPDATE_COMPANY_FAIL: 'UPDATE_COMPANY_FAIL',
};

export default AdminProfileTypes;
