const AdminProfileTypes = {
  UPDATE_COMPANY_START: 'UPDATE_COMPANY_START',
  UPDATE_COMPANY_SUCCESS: 'UPDATE_COMPANY_SUCCESS',
  UPDATE_COMPANY_FAIL: 'UPDATE_COMPANY_FAIL',

  UPDATE_PUBLISH_STATUS_START: 'UPDATE_PUBLISH_STATUS_START',
  UPDATE_PUBLISH_STATUS_SUCCESS: 'UPDATE_PUBLISH_STATUS_SUCCESS',
  UPDATE_PUBLISH_STATUS_FAIL: 'UPDATE_PUBLISH_STATUS_FAIL',
};

export default AdminProfileTypes;
