const BlogsTypes = {
  GET_FEATURED_POSTS_START: 'GET_FEATURED_POSTS_START',
  GET_FEATURED_POSTS_SUCCESS: 'GET_FEATURED_POSTS_SUCCESS',
  GET_FEATURED_POSTS_ERROR: 'GET_FEATURED_POSTS_ERROR',

  GET_FEATURED_POSTS_BY_ID_START: 'GET_FEATURED_POSTS_BY_ID_START',
  GET_FEATURED_POSTS_BY_ID_SUCCESS: 'GET_FEATURED_POSTS_BY_ID_SUCCESS',
  GET_FEATURED_POSTS_BY_ID_ERROR: 'GET_FEATURED_POSTS_BY_ID_ERROR',

  GET_ALL_POSTS_START: 'GET_ALL_POSTS_START',
  GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
  GET_ALL_POSTS_ERROR: 'GET_ALL_POSTS_ERROR',

  GET_POSTS_CATEGORIES_START: 'GET_POSTS_CATEGORIES_START',
  GET_POSTS_CATEGORIES_SUCCESS: 'GET_POSTS_CATEGORIES_SUCCESS',
  GET_POSTS_CATEGORIES_ERROR: 'GET_POSTS_CATEGORIES_ERROR',

  NO_RESULTS: 'NO_RESULTS',
};

export default BlogsTypes;
