const BlogsTypes = {
  GET_FEATURED_POSTS_START: 'GET_FEATURED_POSTS_START',
  GET_FEATURED_POSTS_SUCCESS: 'GET_FEATURED_POSTS_SUCCESS',
  GET_FEATURED_POSTS_ERROR: 'GET_FEATURED_POSTS_ERROR',
};

export default BlogsTypes;
