const BusinessTypes = {
  FETCH_ORGANIZATION: 'FETCH_ORGANIZATION',
  FETCH_ORGANIZATIONS: 'FETCH_ORGANIZATIONS',
  FETCH_FILTERS_OPTIONS: 'FETCH_FILTERS_OPTIONS',
  FETCH_BUSINESSES_METADATA: 'FETCH_BUSINESSES_METADATA',
  FETCH_SEARCH_RESULTS: 'FETCH_SEARCH_RESULTS',
};

export default BusinessTypes;
