const BusinessTypes = {
  FETCH_ORGANIZATION: 'FETCH_ORGANIZATION',
  FETCH_ORGANIZATIONS: 'FETCH_ORGANIZATIONS',
  FETCH_FILTERS_OPTIONS: 'FETCH_FILTERS_OPTIONS',
  FETCH_BUSINESSES_METADATA: 'FETCH_BUSINESSES_METADATA',
  FETCH_SEARCH_RESULTS: 'FETCH_SEARCH_RESULTS',
  FETCH_DATA: 'FETCH_DATA',
  FETCH_DISPLAY_FILTER_OPTIONS: 'FETCH_DISPLAY_FILTER_OPTIONS',
  UPDATE_APPLIED_FILTERS: 'UPDATE_APPLIED_FILTERS',
};

export default BusinessTypes;
