const BusinessTypes = {
  FETCH_BUSINESS: 'FETCH_BUSINESS',
  FETCH_BUSINESSES: 'FETCH_BUSINESSES',
  FETCH_FILTERS_OPTIONS: 'FETCH_FILTERS_OPTIONS',
  FETCH_BUSINESSES_METADATA: 'FETCH_BUSINESSES_METADATA',
};

export default BusinessTypes;
