const EventsTypes = {
  GET_ALL_EVENTS_REQUEST_START: 'GET_ALL_EVENTS_REQUEST_START',
  GET_ALL_EVENTS_REQUEST_SUCCESS: 'GET_ALL_EVENTS_REQUEST_SUCCESS',
  GET_ALL_EVENTS_REQUEST_ERROR: 'GET_ALL_EVENTS_REQUEST_ERROR',

  GET_EVENTS_BY_MONTH_START: 'GET_EVENTS_BY_MONTH_START',
  GET_EVENTS_BY_MONTH_SUCCESS: 'GET_EVENTS_BY_MONTH_SUCCESS',
  GET_EVENTS_BY_MONTH_ERROR: 'GET_EVENTS_BY_MONTH_ERROR',
};

export default EventsTypes;
