const EventsTypes = {
  GET_ALL_EVENTS_REQUEST_START: 'GET_ALL_EVENTS_REQUEST_START',
  GET_ALL_EVENTS_REQUEST_SUCCESS: 'GET_ALL_EVENTS_REQUEST_SUCCESS',
  GET_ALL_EVENTS_REQUEST_ERROR: 'GET_ALL_EVENTS_REQUEST_ERROR',
};

export default EventsTypes;
