const LocationsTypes = {
  GET_LOCATIONS_START: 'GET_LOCATIONS_START',
  GET_LOCATIONS_SUCCESS: 'GET_LOCATIONS_SUCCESS',
  GET_LOCATIONS_ERROR: 'TESTING_SNACKBAR_ERROR',

  GET_LOCATION_BY_ID_START: 'GET_LOCATION_BY_ID_START',
  GET_LOCATION_BY_ID_SUCCESS: 'GET_LOCATION_BY_ID_SUCCESS',
  GET_LOCATION_BY_ID_ERROR: 'GET_LOCATION_BY_ID_ERROR',

  SET_LOADING: 'SET_LOADING',
};

export default LocationsTypes;
