const SnackbarTypes = {
  SHOW_SNACKBAR: 'SHOW_SNACKBAR',
  HIDE_SNACKBAR: 'HIDE_SNACKBAR',
  TESTING_SNACKBAR_REQUEST: 'TESTING_SNACKBAR_REQUEST',
  TESTING_SNACKBAR_SUCCESS: 'TESTING_SNACKBAR_SUCCESS',
  TESTING_SNACKBAR_ERROR: 'TESTING_SNACKBAR_ERROR',
};

export default SnackbarTypes;
