const CreateLocationTypes = {
  CREATE_LOCATION_START: 'CREATE_LOCATION_START',
  CREATE_LOCATION_SUCCESS: 'CREATE_LOCATION_SUCCESS',
  CREATE_LOCATION_ERROR: 'CREATE_LOCATION_ERROR',
};

export default CreateLocationTypes;
