const DeleteLocationTypes = {
  DELETE_LOCATION_START: 'DELETE_LOCATION_START',
  DELETE_LOCATION_SUCCESS: 'DELETE_LOCATION_SUCCESS',
  DELETE_LOCATION_ERROR: 'DELETE_LOCATION_ERROR',
};

export default DeleteLocationTypes;
