const GetLocationByOrganizationTypes = {
  GET_LOCATION_BY_ORGANIZATION_START: 'GET_LOCATION_BY_ORGANIZATION_START',
  GET_LOCATION_BY_ORGANIZATION_SUCCESS: 'GET_LOCATION_BY_ORGANIZATION_SUCCESS',
  GET_LOCATION_BY_ORGANIZATION_ERROR: 'GET_LOCATION_BY_ORGANIZATION_ERROR',

  SET_LOADING: 'SET_LOADING',
};

export default GetLocationByOrganizationTypes;
