export const categories = [
  {id: 10, name: 'health', taggings_count: 0},
  {id: 11, name: 'work', taggings_count: 0},
  {id: 16, name: 'spanish', taggings_count: 0},
  {id: 18, name: 'motorcycle', taggings_count: 0},
  {id: 21, name: 'music', taggings_count: 0},
  {id: 25, name: 'decorations', taggings_count: 0},
  {id: 1, name: 'featured', taggings_count: 6},
  {id: 2, name: 'front page', taggings_count: 6},
  {id: 17, name: 'home', taggings_count: 2},
  {id: 24, name: 'outdoors', taggings_count: 2},
  {id: 20, name: 'clothes', taggings_count: 3},
  {id: 13, name: 'rock', taggings_count: 1},
  {id: 14, name: 'rap', taggings_count: 1},
  {id: 6, name: 'drink', taggings_count: 1},
  {id: 12, name: 'basketball', taggings_count: 1},
  {id: 15, name: 'country', taggings_count: 3},
  {id: 19, name: 'shoes', taggings_count: 1},
  {id: 9, name: 'entertainment', taggings_count: 2},
  {id: 3, name: 'soccer', taggings_count: 1},
  {id: 4, name: 'games', taggings_count: 4},
  {id: 7, name: 'programming', taggings_count: 3},
  {id: 22, name: 'fashion', taggings_count: 3},
  {id: 5, name: 'food', taggings_count: 3},
  {id: 23, name: 'wear', taggings_count: 2},
  {id: 8, name: 'study', taggings_count: 4},
];
